---
#
# Configure UCS, Associate Service Profiles, and Install OS
#
# The hosts group used is provided by the group variable or defaulted to 'ucs'.
# You can specify a specific host (or host group) on the command line:
#   ansible-playbook ... -e group=<your host group>
#   e.g., ansible-playbook server_profiles.yml -e group=TME_Demo
#
- hosts: "{{ group | default('ucs') }}"
  connection: local
  gather_facts: false
  vars:
    # The UCS domain hostname can be set in the inventory or on the command line as needed
    hostname: "{{ inventory_hostname }}"
    # Names for Service Profiles, Policies, and number of Profiles
    template_name: OBA-M3
    org: OBA
    mgmt_vlan: 98
    mgmt99_vlan: 99
    vmotion_vlan: 37
    pxeboot_vlan: 1010
  tasks:
    - block:
        # Configure default pools and other settings
        - import_role:
            name: servers/defaults
          tags: defaults
        # Create vNICs
        - import_role:
            name: servers/network
          tags: network
        # Create vHBAs
        - import_role:
            name: servers/san
          tags: san
        # Configure Service Profile Template with default settings
        - import_role:
            name: servers/service_profile_templates
          tags: templates
      # Use the localhost's environment and Python
      delegate_to: localhost
